### ISSUE TITLE
Kompaktbauformen Hl, Ks

### ISSUE THREAD

**Issue by GravitaBB** [German-Immersive-Railroading-Community/GIRSignals#225]
Moin,

ist geplant, auch Kompakt- / Tunnelbauformen bzw. Zwergsignale von zB Ks und Hl mit in die Mod einzubauen? Gerade für Tunnel wäre das sehr angenehm. 🙃

Grüße

**Comment by Uhutown** [comment]
Moin,
aktuell arbeiten wir gerade an SignalBrücken weshalb wir da schon an Konpaktsignalen sitzen. Du kannst jedoch gerne selbst ein Signalsystem erstellen :)
Auf unserem DC Server kannst du die Docs dafür finden.

**Comment by GravitaBB** [comment]
Joa danke für die schnelle Antwort um die Zeit 🙃

Naja, tatsächlich hab ich da wenig Zeit für, aber wenn ihr daran bereits am Arbeiten seid, klingt das ja gut. Danke auf jeden Fall auch für eure Arbeit!
