### ISSUE TITLE
Signalsteuerer Einstellungs Problem

### ISSUE THREAD

**Issue by Schweineohren** [German-Immersive-Railroading-Community/GIRSignals#98]
Hallo, 
Ich habe eine Einzelspielerwelt, wo ich mir ein kleines Stellwerk gebaut habe und da mit Redstone die Signale steuere, nur das Problem ist, wenn ich Minecraft schließe und dann in diese Welt neu beitrete, das in den Signalsteuerer die Einzelansteurungen Falsch sind, zum Beispiel sollte es das Vorsignal steuern steuert aber dann das ZS 7 Signal. Aber die Einstellungen von den Vorsignal werden gespeichert, also ich kann dann wieder auf Vorsignal stellen und es funktioniert wieder alles. Gibt es da irgendeine Lösung wie ich das verstellen verhinder kann oder ist der Fehler schon bekannt?

**Comment by MrTroble** [comment]
Hallo @Schweineohren,

das Issue ist bereits bekannt und wir arbeiten derzeit an einem grossen internen UI Update mit dem die reliability der Einstellungen generell verbessert werden.

Wir haben leider derzeit kein Workaround dafuer, wenn es aber verbesserungs vorschlaege bezueglich der UI gibt, gerne einbringen.

Cheers
~MrTroble

**Comment by MrTroble** [comment]
@Schweineohren nur mal kurz als update das erste Teil des updates wird gerade in #103 getestet. Dort ist das neue Redstone system leider noch nicht drinn, das wird allerdings so bald wie moeglich nach geliefert

**Comment by MrTroble** [comment]
So das sollte mit dem #106 Update gefixed sein
